version: '3.7'
services:
  authentication:
    build:
      context: ..
      target: DEV
      dockerfile: ./docker/Dockerfile
    ports:
      - "3000:3000"
      - "9229:9229"
    environment:
      - DB_HOST=mongo
    volumes:
      - "../src:/src"
      - "./certificates:/certificates"
  mongo:
    image: mongo:4.2.0
    ports:
      - 27017:27017